### 1.	Create a 2D array and print the dim and shape

In [4]:
import numpy as np
import pandas as pd

In [145]:
twodim = np.array([[10,20,30,40,50],[100,200,300,400,500]])

In [146]:
print(twodim.ndim)

2


In [147]:
twodim.shape

(2, 5)

### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [24]:
arr = np.arange(20)
slic = slice(10,15,1)
arr[slic]

array([10, 11, 12, 13, 14])

### 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 

In [97]:
arr1 = np.array([[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]])
arr2 = np.array([[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]])

In [92]:
arr1.shape

(7, 5)

In [98]:
arr2.shape

(7, 5)

In [99]:
# Addtion of arr1 and arr2
addarr = np.add(arr1,arr2)
# Subtraction of arr1 and arr2
subarr = np.subtract(arr1,arr2)
# Multiplication of arr1 and arr2
mularr = np.multiply(arr1,arr2)
# Division of arr1 and arr2
divarr = np.divide(arr1,arr2)

In [100]:
print(addarr)
print(subarr)
print(mularr)
print(divarr)


[[15 25 35 45 55]
 [15 25 35 45 55]
 [15 25 35 45 55]
 [15 25 35 45 55]
 [15 25 35 45 55]
 [15 25 35 45 55]
 [15 25 35 45 55]]
[[ 5 15 25 35 45]
 [ 5 15 25 35 45]
 [ 5 15 25 35 45]
 [ 5 15 25 35 45]
 [ 5 15 25 35 45]
 [ 5 15 25 35 45]
 [ 5 15 25 35 45]]
[[ 50 100 150 200 250]
 [ 50 100 150 200 250]
 [ 50 100 150 200 250]
 [ 50 100 150 200 250]
 [ 50 100 150 200 250]
 [ 50 100 150 200 250]
 [ 50 100 150 200 250]]
[[ 2.  4.  6.  8. 10.]
 [ 2.  4.  6.  8. 10.]
 [ 2.  4.  6.  8. 10.]
 [ 2.  4.  6.  8. 10.]
 [ 2.  4.  6.  8. 10.]
 [ 2.  4.  6.  8. 10.]
 [ 2.  4.  6.  8. 10.]]


### 4.	Create 2 incompatible arrays for broadcast and print out the error

In [73]:
np.array([[10,20,30,40,50],[100,200,300,400]])

C:\Users\RAJKUMAR\AppData\Local\Temp/ipykernel_7232/4040489115.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[10,20,30,40,50],[100,200,300,400]])


array([list([10, 20, 30, 40, 50]), list([100, 200, 300, 400])],
      dtype=object)

### 5.	Create two arrays of any dimension and perform vstack and hstack

In [105]:
arr1 = np.array([10,20,30,40,50,60,70])
arr2 = np.array([5,5,5,5,5,5,5])

Stack: Join a sequence of arrays along a new axis.

In [80]:
np.stack((arr1,arr2), axis=0)

array([[10, 20, 30, 40, 50, 60, 70],
       [ 5,  5,  5,  5,  5,  5,  5]])

In [101]:
np.stack((arr1,arr2), axis=1)

array([[[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]],

       [[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]],

       [[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]],

       [[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]],

       [[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]],

       [[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]],

       [[10, 20, 30, 40, 50],
        [ 5,  5,  5,  5,  5]]])

In [109]:
#Stack arrays in sequence vertically (row wise).
np.vstack((arr1,arr2))

array([[10, 20, 30, 40, 50, 60, 70],
       [ 5,  5,  5,  5,  5,  5,  5]])

In [116]:
#Stack arrays in sequence horizontally (column wise).
np.hstack((arr1,arr2))

array([10, 20, 30, 40, 50, 60, 70,  5,  5,  5,  5,  5,  5,  5])

### 6.	Append two arrays using axis = 0 and axis = 1

In [138]:
arr1 = np.array([[10,20,30],[5,5,5]])

In [139]:
arr1

array([[10, 20, 30],
       [ 5,  5,  5]])

In [140]:
#Append values to the end of an array in rowwise.
np.append(arr1,[[40,50,60],[5,5,5]],axis=0)

array([[10, 20, 30],
       [ 5,  5,  5],
       [40, 50, 60],
       [ 5,  5,  5]])

In [142]:
#Append values to the end of an array in the columnwise.
np.append(arr1,[[40,50,60],[5,5,5]],axis=1)

array([[10, 20, 30, 40, 50, 60],
       [ 5,  5,  5,  5,  5,  5]])

### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [12]:
list1 = [[1,20221,'raj','33','s.devloper',123456,'rajgg.xx.com','M'],
         [2,20222,'tom','34','s.devloper',12346,'tomgg.xx.com','M'],
         [3,20223,'jack','30','devloper',123456,'jackgg.xx.com','M'],
         [4,20224,'Jessy','28','s.devloper',12346,'jesmgg.xx.com','F']]
pdlist = pd.DataFrame(list1,columns =['SLNO','EMP ID','NAME','AGE','DESIG','CON NUMBER','MAIL ID','GENDER'] )
pdlist

SLNO  EMP ID   NAME AGE       DESIG  CON NUMBER        MAIL ID GENDER
0     1   20221    raj  33  s.devloper      123456   rajgg.xx.com      M
1     2   20222    tom  34  s.devloper       12346   tomgg.xx.com      M
2     3   20223   jack  30    devloper      123456  jackgg.xx.com      M
3     4   20224  Jessy  28  s.devloper       12346  jesmgg.xx.com      F

### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [21]:
iplqlfier = {'CSK':[12,10,2,40,6,4,2,9.0],'RCB':[12,8,4,32,8,6,2,8.6],'MI':[12,9,3,36,5,3,2,8.8],'KOL':[12,7,5,28,5,2,3,9.0]}
pdipl = pd.DataFrame(iplqlfier, index=['TotalMatch', 'Win', 'Loss','Points','Toss Win','Bat First','Field First','Fair Play'])
pdipl

CSK   RCB    MI   KOL
TotalMatch   12.0  12.0  12.0  12.0
Win          10.0   8.0   9.0   7.0
Loss          2.0   4.0   3.0   5.0
Points       40.0  32.0  36.0  28.0
Toss Win      6.0   8.0   5.0   5.0
Bat First     4.0   6.0   3.0   2.0
Field First   2.0   2.0   2.0   3.0
Fair Play     9.0   8.6   8.8   9.0

### 9.	Use loc and ilocto subset the data for the above dataframe

In [28]:
#Locate is used to find the Integer or string name
pdipl.loc[:'Points']

CSK   RCB    MI   KOL
TotalMatch  12.0  12.0  12.0  12.0
Win         10.0   8.0   9.0   7.0
Loss         2.0   4.0   3.0   5.0
Points      40.0  32.0  36.0  28.0

In [29]:
#iLocate is used to find by the integer value
pdipl.iloc[:4]

CSK   RCB    MI   KOL
TotalMatch  12.0  12.0  12.0  12.0
Win         10.0   8.0   9.0   7.0
Loss         2.0   4.0   3.0   5.0
Points      40.0  32.0  36.0  28.0

### 10.	How to check the total number of not null values in a column?

In [31]:
pdipl['CSK'].notnull()

TotalMatch     True
Win            True
Loss           True
Points         True
Toss Win       True
Bat First      True
Field First    True
Fair Play      True
Name: CSK, dtype: bool

In [36]:
# to get the value in Dataframe
filtered_df = pdipl[pdipl['CSK'].notnull()]
filtered_df

CSK   RCB    MI   KOL
TotalMatch   12.0  12.0  12.0  12.0
Win          10.0   8.0   9.0   7.0
Loss          2.0   4.0   3.0   5.0
Points       40.0  32.0  36.0  28.0
Toss Win      6.0   8.0   5.0   5.0
Bat First     4.0   6.0   3.0   2.0
Field First   2.0   2.0   2.0   3.0
Fair Play     9.0   8.6   8.8   9.0

In [37]:
pdipl['CSK'].isnull()

TotalMatch     False
Win            False
Loss           False
Points         False
Toss Win       False
Bat First      False
Field First    False
Fair Play      False
Name: CSK, dtype: bool

In [38]:
# to get the value in Dataframe
filtered_df = pdipl[pdipl['CSK'].isnull()]
filtered_df

Empty DataFrame
Columns: [CSK, RCB, MI, KOL]
Index: []

### 11.	Create a dataframe with missing values and fill them all with 100

In [44]:
list2 = [[1,20221,'raj','33','s.devloper',12345,'rajgg.xx.com','M'],
         [2,20222,'tom','34','s.devloper',12346,'tomgg.xx.com','M'],
         [3,20223,'jack','30','devloper',123456,'jackgg.xx.com','M'],
         [4,20224,'Jessy','28','s.devloper',1234,'jesmgg.xx.com','F']]
pdlist1 = pd.DataFrame(list2,columns =['SLNO','EMP ID','NAME','AGE','DESIG','CON NUMBER','MAIL ID','GENDER'] )
pdlist1

SLNO  EMP ID   NAME AGE       DESIG  CON NUMBER        MAIL ID GENDER
0     1   20221    raj  33  s.devloper       12345   rajgg.xx.com      M
1     2   20222    tom  34  s.devloper       12346   tomgg.xx.com      M
2     3   20223   jack  30    devloper      123456  jackgg.xx.com      M
3     4   20224  Jessy  28  s.devloper        1234  jesmgg.xx.com      F

In [46]:
pdlist1 = pdlist1.reindex([0,1,2,3,4])

In [47]:
pdlist1

SLNO   EMP ID   NAME  AGE       DESIG  CON NUMBER        MAIL ID GENDER
0   1.0  20221.0    raj   33  s.devloper     12345.0   rajgg.xx.com      M
1   2.0  20222.0    tom   34  s.devloper     12346.0   tomgg.xx.com      M
2   3.0  20223.0   jack   30    devloper    123456.0  jackgg.xx.com      M
3   4.0  20224.0  Jessy   28  s.devloper      1234.0  jesmgg.xx.com      F
4   NaN      NaN    NaN  NaN         NaN         NaN            NaN    NaN

In [49]:
pdlist1.fillna(100, inplace=True)
pdlist1

SLNO   EMP ID   NAME  AGE       DESIG  CON NUMBER        MAIL ID GENDER
0    1.0  20221.0    raj   33  s.devloper     12345.0   rajgg.xx.com      M
1    2.0  20222.0    tom   34  s.devloper     12346.0   tomgg.xx.com      M
2    3.0  20223.0   jack   30    devloper    123456.0  jackgg.xx.com      M
3    4.0  20224.0  Jessy   28  s.devloper      1234.0  jesmgg.xx.com      F
4  100.0    100.0    100  100         100       100.0            100    100

### 12.	Create a dataframe with missing values and drop the null records

In [53]:
list2 = [[1,20221,'raj','33','s.devloper',12345,'rajgg.xx.com','M'],
         [2,20222,'tom','34','s.devloper',12346,'tomgg.xx.com','M'],
         [3,20223,'jack','30','devloper',123456,'jackgg.xx.com','M'],
         [4,20224,'Jessy','28','s.devloper',1234,'jesmgg.xx.com','F']]
pdlist1 = pd.DataFrame(list2,columns =['SLNO','EMP ID','NAME','AGE','DESIG','CON NUMBER','MAIL ID','GENDER'] )
pdlist1

SLNO  EMP ID   NAME AGE       DESIG  CON NUMBER        MAIL ID GENDER
0     1   20221    raj  33  s.devloper       12345   rajgg.xx.com      M
1     2   20222    tom  34  s.devloper       12346   tomgg.xx.com      M
2     3   20223   jack  30    devloper      123456  jackgg.xx.com      M
3     4   20224  Jessy  28  s.devloper        1234  jesmgg.xx.com      F

In [54]:
pdlist1 = pdlist1.reindex([0,1,2,3,4])
pdlist1

SLNO   EMP ID   NAME  AGE       DESIG  CON NUMBER        MAIL ID GENDER
0   1.0  20221.0    raj   33  s.devloper     12345.0   rajgg.xx.com      M
1   2.0  20222.0    tom   34  s.devloper     12346.0   tomgg.xx.com      M
2   3.0  20223.0   jack   30    devloper    123456.0  jackgg.xx.com      M
3   4.0  20224.0  Jessy   28  s.devloper      1234.0  jesmgg.xx.com      F
4   NaN      NaN    NaN  NaN         NaN         NaN            NaN    NaN

In [55]:
pdlist1.dropna()

SLNO   EMP ID   NAME AGE       DESIG  CON NUMBER        MAIL ID GENDER
0   1.0  20221.0    raj  33  s.devloper     12345.0   rajgg.xx.com      M
1   2.0  20222.0    tom  34  s.devloper     12346.0   tomgg.xx.com      M
2   3.0  20223.0   jack  30    devloper    123456.0  jackgg.xx.com      M
3   4.0  20224.0  Jessy  28  s.devloper      1234.0  jesmgg.xx.com      F

### 13.	Perform following aggregation task on below table
### a.	Get the average age group by Regrion
### b.	Get the sum of Age and Validation group by Hair color and then reset the index
### c.	Get the man and the median of Age group by Region


In [68]:
pdlist2 = pd.DataFrame([[25,'Black','SW',1],
                        [30,'Black','NW',1],
                        [45,'Red','NE',1],
                        [35,'Blond','SW',0],
                        [33,'Brown','SW',0],
                        [35,'Brown','NE',0],
                        [25,'Black','SW',0],
                        [52,'Brown','SE',0],
                        [21,'Blond','SW',1],
                        [24,'Blond','NE',0],
                        [48,'Black','SW',1],
                        [22,'Black','SW',0],
                        [27,'Brown','NE',0],
                        [28,'Black','SE',1],
                        [21,'Blond','SE',1],
                        [51,'Black','NW',0],
                        [23,'Brown','SE',1],                        
                       ]
                       ,columns =['AGE','HAIR COLOR','US REGION','VALIDATION'] )

In [69]:
pdlist2

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [85]:
pdlist2.groupby(['US REGION'])['AGE'].count()

US REGION
NE    4
NW    2
SE    4
SW    7
Name: AGE, dtype: int64

In [73]:
pdlist2.groupby(['US REGION'])['AGE'].sum()

US REGION
NE    131
NW     81
SE    124
SW    209
Name: AGE, dtype: int64

In [87]:
# M1: Get the average age group by Regrion
pdlist2.groupby(['US REGION'])['AGE'].sum()/pdlist2.groupby(['US REGION'])['AGE'].count()

US REGION
NE    32.750000
NW    40.500000
SE    31.000000
SW    29.857143
Name: AGE, dtype: float64

In [89]:
# M2: Get the average age group by Regrion
pdlist2.groupby(['US REGION'])['AGE'].mean().reset_index()

US REGION        AGE
0        NE  32.750000
1        NW  40.500000
2        SE  31.000000
3        SW  29.857143

In [90]:
 #Get the sum of Age and Validation group by Hair color and then reset the index
pdlist2.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()
    

C:\Users\RAJKUMAR\AppData\Local\Temp/ipykernel_11500/2726530517.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  pdlist2.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()


HAIR COLOR  AGE  VALIDATION
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

In [91]:
#c.	Get the man and the median of Age group by Region
pdlist2.groupby(['US REGION'])['AGE'].agg([np.mean, np.median]).reset_index()

US REGION       mean  median
0        NE  32.750000    31.0
1        NW  40.500000    40.5
2        SE  31.000000    25.5
3        SW  29.857143    25.0

### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [98]:
pdlist3 = pdlist2.iloc[:10]
pdlist4 = pdlist2.iloc[10:]


In [97]:
pdlist3

AGE HAIR COLOR US REGION  VALIDATION
0   25      Black        SW           1
1   30      Black        NW           1
2   45        Red        NE           1
3   35      Blond        SW           0
4   33      Brown        SW           0
5   35      Brown        NE           0
6   25      Black        SW           0
7   52      Brown        SE           0
8   21      Blond        SW           1
9   24      Blond        NE           0

In [100]:
pdlist4

AGE HAIR COLOR US REGION  VALIDATION
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [ ]:
pdlist3.merge(pdlist4, on='SubjectId', how = 'left')

In [101]:
pd.merge(pdlist3, pdlist4, on='US REGION')

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     48        Black   
1      25        Black        SW             1     22        Black   
2      35        Blond        SW             0     48        Black   
3      35        Blond        SW             0     22        Black   
4      33        Brown        SW             0     48        Black   
5      33        Brown        SW             0     22        Black   
6      25        Black        SW             0     48        Black   
7      25        Black        SW             0     22        Black   
8      21        Blond        SW             1     48        Black   
9      21        Blond        SW             1     22        Black   
10     30        Black        NW             1     51        Black   
11     45          Red        NE             1     27        Brown   
12     35        Brown        NE             0     27        Brown   
13     24        Blond        NE             0     27        Brown   
14     52        Brown        SE             0     28        Black   
15     52        Brown        SE             0     21        Blond   
16     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             1

In [102]:
pdlist3.merge(pdlist4, on='US REGION', how = 'left')

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     48        Black   
1      25        Black        SW             1     22        Black   
2      30        Black        NW             1     51        Black   
3      45          Red        NE             1     27        Brown   
4      35        Blond        SW             0     48        Black   
5      35        Blond        SW             0     22        Black   
6      33        Brown        SW             0     48        Black   
7      33        Brown        SW             0     22        Black   
8      35        Brown        NE             0     27        Brown   
9      25        Black        SW             0     48        Black   
10     25        Black        SW             0     22        Black   
11     52        Brown        SE             0     28        Black   
12     52        Brown        SE             0     21        Blond   
13     52        Brown        SE             0     23        Brown   
14     21        Blond        SW             1     48        Black   
15     21        Blond        SW             1     22        Black   
16     24        Blond        NE             0     27        Brown   

    VALIDATION_y  
0              1  
1              0  
2              0  
3              0  
4              1  
5              0  
6              1  
7              0  
8              0  
9              1  
10             0  
11             1  
12             1  
13             1  
14             1  
15             0  
16             0

In [103]:
pdlist3.merge(pdlist4, on='US REGION', how = 'right')

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     48        Black   
1      35        Blond        SW             0     48        Black   
2      33        Brown        SW             0     48        Black   
3      25        Black        SW             0     48        Black   
4      21        Blond        SW             1     48        Black   
5      25        Black        SW             1     22        Black   
6      35        Blond        SW             0     22        Black   
7      33        Brown        SW             0     22        Black   
8      25        Black        SW             0     22        Black   
9      21        Blond        SW             1     22        Black   
10     45          Red        NE             1     27        Brown   
11     35        Brown        NE             0     27        Brown   
12     24        Blond        NE             0     27        Brown   
13     52        Brown        SE             0     28        Black   
14     52        Brown        SE             0     21        Blond   
15     30        Black        NW             1     51        Black   
16     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              1  
3              1  
4              1  
5              0  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             1  
14             1  
15             0  
16             1

### 15.	Split the below table and perform concat row wise and column wise

In [105]:
pdlist3

AGE HAIR COLOR US REGION  VALIDATION
0   25      Black        SW           1
1   30      Black        NW           1
2   45        Red        NE           1
3   35      Blond        SW           0
4   33      Brown        SW           0
5   35      Brown        NE           0
6   25      Black        SW           0
7   52      Brown        SE           0
8   21      Blond        SW           1
9   24      Blond        NE           0

In [106]:
pdlist4

AGE HAIR COLOR US REGION  VALIDATION
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [107]:
pd.concat([pdlist3, pdlist4]) #Row wise operation

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [108]:
pd.concat([pdlist3, pdlist4],axis=1) #column wise operation

AGE HAIR COLOR US REGION  VALIDATION   AGE HAIR COLOR US REGION  \
0   25.0      Black        SW         1.0   NaN        NaN       NaN   
1   30.0      Black        NW         1.0   NaN        NaN       NaN   
2   45.0        Red        NE         1.0   NaN        NaN       NaN   
3   35.0      Blond        SW         0.0   NaN        NaN       NaN   
4   33.0      Brown        SW         0.0   NaN        NaN       NaN   
5   35.0      Brown        NE         0.0   NaN        NaN       NaN   
6   25.0      Black        SW         0.0   NaN        NaN       NaN   
7   52.0      Brown        SE         0.0   NaN        NaN       NaN   
8   21.0      Blond        SW         1.0   NaN        NaN       NaN   
9   24.0      Blond        NE         0.0   NaN        NaN       NaN   
10   NaN        NaN       NaN         NaN  48.0      Black        SW   
11   NaN        NaN       NaN         NaN  22.0      Black        SW   
12   NaN        NaN       NaN         NaN  27.0      Brown        NE   
13   NaN        NaN       NaN         NaN  28.0      Black        SE   
14   NaN        NaN       NaN         NaN  21.0      Blond        SE   
15   NaN        NaN       NaN         NaN  51.0      Black        NW   
16   NaN        NaN       NaN         NaN  23.0      Brown        SE   

    VALIDATION  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          NaN  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0